import http from "utils/http.js";
export const goods_api = ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=&type=&channel_type=")
export const goods_api_basketball = ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=&type=basketball&channel_type=")
export const goods_api_running = ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=&type=running&channel_type=")
export const goods_api_fitness = ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=&type=fitness&channel_type=")
export const goods_api_trend = ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=&type=freestyle&channel_type=")
export const sports_api_basketball = ()=>http("get","/abc/sports/getNews?pageSize=20&param_str=1564945214_1564993449_2&type=basketball&newsId=&channel_type=")
export const hotSearch= ()=>http("get","/abc/search/hotSearch")
export const goods_api_two= ()=>http("get","/abc/homefis/getNews?pageSize=20&param_str=1565252204%3A3%3A&type=&channel_type=")
export const goods_search= (keywords)=>http("get","/abc/search/relatedKeywords",{keywords:keywords})
export const goods_details= (id,tag_id=0,page=1,page_size=5,sort='hot')=>http("get","/abc/sports/getComment",{id:id,tag_id:tag_id,page:page,page_size:page_size,sort:sort})
export const goods_search_detail= (keywords,page=1,page_size=3)=>http("get","/abc/search/allweb",{keywords:keywords,page:page,page_size:page_size})
export const goods_search_detail1= (keywords)=>http("get","/abc/search/searchAd",{keywords:keywords})
export const goods_search_detail2= (keywords,page=1,page_size=3,type='shaiwu')=>http("get","/abc/search",{keywords:keywords,page:page,page_size:page_size,type:type})
export const goods_search_detail3= (keywords,page=1,page_size=3,type='goods')=>http("get","/abc/search",{keywords:keywords,page:page,page_size:page_size,type:type})
export const goods_search_detail4= (keywords,page=1,page_size=3,type='pic')=>http("get","/abc/search",{keywords:keywords,page:page,page_size:page_size,type:type})
export const goods_search_detail5= (keywords,page=1,page_size=3,type='news')=>http("get","/abc/search",{keywords:keywords,page:page,page_size:page_size,type:type})
